### ISSUE TITLE
make it so we can add our own illegal items

### ISSUE THREAD

**Issue by s0daa** [zeroBzeroT/AntiIllegals#11]

**Comment by Pr3roxDLC** [comment]
What exactly do you want? Is a config file what you are looking for?

**Comment by gqbe** [comment]
> What exactly do you want? Is a config file what you are looking for?

Yes, like being able to delete certain blacklisted items or add them.

**Comment by bierdosenhalter** [comment]
added to the config. add materials to illegalMaterials to block them
