### ISSUE TITLE
Config for Handling Shulker + Books

### ISSUE THREAD

**Issue by blockswerker** [zeroBzeroT/AntiIllegals#12]
By default this plugin kicks all books out of a shulker if there are > 5 books, no matter how big or small they are. It would be nice if we could opt-in to that behavior, or if there was a byte check for book size to prevent book bans.

Limiting shulkers to just 5 books is difficult for book collectors and I am still testing but it seems that m moving shulkers in e-chests can result in deleted books.

**Comment by bierdosenhalter** [comment]
set maxBooksInShulker in the config to -1 to not use this feature
