### ISSUE TITLE
i had a server that had a white stained glass block that was enchanted sharpness level 5 and the plugin only reverted the enchantments to level 1 instead of removing them

### ISSUE THREAD

**Issue by emils2** [zeroBzeroT/AntiIllegals#46]
![3ee](https://user-images.githubusercontent.com/124498314/226377662-c84dc539-baaa-49c2-a13b-090948807436.PNG)

**Comment by GeorgeRNG** [comment]
This is likely because the `itemsWithLore` config option, which is on by default
When enable it checks if *item is not enchant-able by the enchantment, is not a weapon or armor* and makes it level 1
