### ISSUE TITLE
add helper methods for checkItemStack

### ISSUE THREAD

**Issue by crxyne** [zeroBzeroT/AntiIllegals#75]
any time checkItemStack is used in Events, it checks if the ItemState returned by the method is ItemState.illegal. this creates a bypass for things like overstacked items when they are picked up from the ground, because in order to fully revert the item, the event needs to be cancelled. because reverting overstacked items only results in ItemState.wasFixed, this is not handled correctly (as well as in other places)

**Comment by nothub** [comment]
resolved with #81
