### ISSUE TITLE
wrong logic in swap offhand items event

### ISSUE THREAD

**Issue by crxyne** [zeroBzeroT/AntiIllegals#76]
the [check for when offhand items are swapped](https://github.com/zeroBzeroT/AntiIllegals/blob/81f29e086b41ccf9faf67b9bd3a58e15ba798770/src/main/java/org/zeroBzeroT/antiillegals/Events.java#L103) is flawed, as it checks if the item to revert is null AND illegal (which is never the case, air is not illegal). changing the first == to != should fix this, same goes for [the check below it](https://github.com/zeroBzeroT/AntiIllegals/blob/81f29e086b41ccf9faf67b9bd3a58e15ba798770/src/main/java/org/zeroBzeroT/antiillegals/Events.java#L107)

**Comment by nothub** [comment]
resolved with #81
