### ISSUE TITLE
unnecessary check for whether the entity is a player in pickup item event

### ISSUE THREAD

**Issue by crxyne** [zeroBzeroT/AntiIllegals#77]
in [the pickup item event](https://github.com/zeroBzeroT/AntiIllegals/blob/81f29e086b41ccf9faf67b9bd3a58e15ba798770/src/main/java/org/zeroBzeroT/antiillegals/Events.java#L81), an unnecessary check for whether the entity is a player is performed. this makes the code a little bit verbose, but more importantly it allows entities with possible equipment to hold illegal items.

**Comment by nothub** [comment]
resolved with #81

**Comment by nothub** [comment]
resolved with #81
