### ISSUE TITLE
duplicated code

### ISSUE THREAD

**Issue by crxyne** [zeroBzeroT/AntiIllegals#79]
there is duplicated code in [AntiIllegals.java#L159](https://github.com/zeroBzeroT/AntiIllegals/blob/7ffff60dce48b002c5e829ccb5c46c9301132ddb/src/main/java/org/zeroBzeroT/antiillegals/AntiIllegals.java#L159) and [ShulkeredBooksCleaner.java#L16](https://github.com/zeroBzeroT/AntiIllegals/blob/7ffff60dce48b002c5e829ccb5c46c9301132ddb/src/main/java/org/zeroBzeroT/antiillegals/ShulkeredBooksCleaner.java#L16)

**Comment by nothub** [comment]
resolved with #81

**Comment by nothub** [comment]
resolved with #81
