### ISSUE TITLE
unnecessary extra logic in block place event check

### ISSUE THREAD

**Issue by crxyne** [zeroBzeroT/AntiIllegals#80]
the items illegal state is (kind of) checked twice, first time [here](https://github.com/zeroBzeroT/AntiIllegals/blob/7ffff60dce48b002c5e829ccb5c46c9301132ddb/src/main/java/org/zeroBzeroT/antiillegals/Events.java#L56), the second time again, but fully, [here](https://github.com/zeroBzeroT/AntiIllegals/blob/7ffff60dce48b002c5e829ccb5c46c9301132ddb/src/main/java/org/zeroBzeroT/antiillegals/Events.java#L61). this can be done cleaner by replacing the first check with the second and seeing if the returned ItemState is illegal.

**Comment by nothub** [comment]
resolved with #81
